version: "2"

volumes:
    postgres-volume:
        external: true

services:
    postgres:   
        image: yin2/postgres-9.3:latest
        container_name: "postgres"
        volumes:
            - postgres-volume:/var/lib/postgresql/9.3/main:Z
        networks:
            - app-net
    
    elasticsearch:
        image: yin2/elasticsearch-1.7:1.7.3
        container_name: "elasticsearch"
        volumes:
            - ./elasticsearch-data:/elasticsearch/data
        networks:
            - app-net

    annotator-store:
        image: yin2/annotator-store
        environment:
            - ELASTICSEARCH_HOST=elasticsearch
        depends_on: 
            - "elasticsearch"
        command: bash -c "sleep 10; python run.py"
        ports:
            - 5000:5000
        container_name: "annotator-store"
        networks:
            - app-net

    apache2:
        image: yin2/apache2:2.4
        ports:
            - 8085:80    
        container_name: "apache2"
        networks:
            - app-net

    dbmi-annotator:
        image: yin2/dbmi-annotator:latest
        environment:
            - PGHOST=postgres
            - PGDATABASE=dbmiannotator
            - PGUSER=dbmiannotator
            - ELASTICSEARCH_HOST=elasticsearch
            - APACHE2_HOST=apache2
        depends_on: 
            - "postgres"
        container_name: "dbmi-annotator"
        networks:
            - app-net

networks:
    app-net:
        driver: bridge